---
- name: Set up environment for Sentinel API 
  hosts: sentinel 
  become: true
  gather_facts: False
  tasks: 
    - name: Sleep for 10 seconds and continue with play. 
      wait_for:
        timeout: 10 
    - name: Install gcc
      command: sudo yum install -y gcc-c++ make
    - name: Get node source 
      shell: curl -sL https://rpm.nodesource.com/setup_14.x | sudo -E bash -
      register: result
    - name: Install node
      command: sudo yum install -y nodejs
    - name: Git clone the repository
      retries: 3
      git:
        repo: https://github.com/Sentinel-PaaS/sentinel-api-2.git
        dest: /home/ec2-user/sentinel-api-2
        clone: yes
    - name: Install pm2
      npm:
        name: pm2
        global: yes
    - name: Install Sentinel API dependencies
      command: npm install
      args: 
        chdir: /home/ec2-user/sentinel-api-2/
    # TODO: use PM2 to start the API server
    # - name: Start API server
    #   command: pm2 start "npm start" --name "hello"
    #   args: 
    #     chdir: /home/ec2-user/sentinel-api-2/
